//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neoStockMasterv2.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neoStockMasterv2.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying.
        /// </summary>
        internal static string Alış {
            get {
                return ResourceManager.GetString("Alış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string Ana_Menü {
            get {
                return ResourceManager.GetString("Ana Menü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracted Shipping Company.
        /// </summary>
        internal static string Anlaşmalı_Kargo_Şirketi {
            get {
                return ResourceManager.GetString("Anlaşmalı Kargo Şirketi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Bilgilerimi_Hatırlat {
            get {
                return ResourceManager.GetString("Bilgilerimi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Birim_Miktarı {
            get {
                return ResourceManager.GetString("Birim Miktarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Tables.
        /// </summary>
        internal static string Bütün_Tabloları_Genişlet {
            get {
                return ResourceManager.GetString("Bütün Tabloları Genişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Rates.
        /// </summary>
        internal static string Çarpraz_Kurlar {
            get {
                return ResourceManager.GetString("Çarpraz Kurlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Çevrilen {
            get {
                return ResourceManager.GetString("Çevrilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Çevrilmek_İstenen {
            get {
                return ResourceManager.GetString("Çevrilmek İstenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Çıkış {
            get {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Diğer {
            get {
                return ResourceManager.GetString("Diğer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Information.
        /// </summary>
        internal static string Döviz_Bilgisi {
            get {
                return ResourceManager.GetString("Döviz Bilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Düzenle {
            get {
                return ResourceManager.GetString("Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Address.
        /// </summary>
        internal static string E_Mail_Adresinizi_Yazınız {
            get {
                return ResourceManager.GetString("E-Mail Adresinizi Yazınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Added.
        /// </summary>
        internal static string Eklenecek {
            get {
                return ResourceManager.GetString("Eklenecek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EngFlag {
            get {
                object obj = ResourceManager.GetObject("EngFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English2 {
            get {
                return ResourceManager.GetString("English2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event History.
        /// </summary>
        internal static string Etkinlik_Geçmişi {
            get {
                return ResourceManager.GetString("Etkinlik Geçmişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string Excel_e_Aktar {
            get {
                return ResourceManager.GetString("Excel\'e Aktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Details.
        /// </summary>
        internal static string Fiyat_Detayları {
            get {
                return ResourceManager.GetString("Fiyat Detayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing - Order Form.
        /// </summary>
        internal static string Fiyat_Hesaplama___Sipariş_Oluşturma {
            get {
                return ResourceManager.GetString("Fiyat Hesaplama - Sipariş Oluşturma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Prices.
        /// </summary>
        internal static string Fiyatları_Kilitle {
            get {
                return ResourceManager.GetString("Fiyatları Kilitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string Genişlet {
            get {
                return ResourceManager.GetString("Genişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In Screen.
        /// </summary>
        internal static string Giriş_Ekranı {
            get {
                return ResourceManager.GetString("Giriş Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Güncelle {
            get {
                return ResourceManager.GetString("Güncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Remember.
        /// </summary>
        internal static string ID_Hatırla {
            get {
                return ResourceManager.GetString("ID Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string İndirim {
            get {
                return ResourceManager.GetString("İndirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP History.
        /// </summary>
        internal static string IP_Geçmişi {
            get {
                return ResourceManager.GetString("IP Geçmişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Menu.
        /// </summary>
        internal static string İşlem_Menüsü {
            get {
                return ResourceManager.GetString("İşlem Menüsü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Action.
        /// </summary>
        internal static string İşlemi_Seç {
            get {
                return ResourceManager.GetString("İşlemi Seç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Days.
        /// </summary>
        internal static string Kalan_Gün_Sayısı {
            get {
                return ResourceManager.GetString("Kalan Gün Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin.
        /// </summary>
        internal static string Kâr_Yüzdesi {
            get {
                return ResourceManager.GetString("Kâr Yüzdesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string Kargo {
            get {
                return ResourceManager.GetString("Kargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Karşılaştır {
            get {
                return ResourceManager.GetString("Karşılaştır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Screen.
        /// </summary>
        internal static string Kayıt_Ekranı {
            get {
                return ResourceManager.GetString("Kayıt Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Kayıt_Ol {
            get {
                return ResourceManager.GetString("Kayıt Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string Kayıt_Tarihi {
            get {
                return ResourceManager.GetString("Kayıt Tarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Registered.
        /// </summary>
        internal static string Kayıtlı_Gün_Sayısı {
            get {
                return ResourceManager.GetString("Kayıtlı Gün Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Kopyala {
            get {
                return ResourceManager.GetString("Kopyala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string Kullanıcı_Bilgileri {
            get {
                return ResourceManager.GetString("Kullanıcı Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string Kullanıcı_Detayları {
            get {
                return ResourceManager.GetString("Kullanıcı Detayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Kullanıcı_İsmi {
            get {
                return ResourceManager.GetString("Kullanıcı İsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Username.
        /// </summary>
        internal static string Kullanıcı_İsmini_Hatırlat {
            get {
                return ResourceManager.GetString("Kullanıcı İsmini Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Verification.
        /// </summary>
        internal static string Kullanıcı_Onaylama {
            get {
                return ResourceManager.GetString("Kullanıcı Onaylama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        internal static string Kullanıcı_Paneli {
            get {
                return ResourceManager.GetString("Kullanıcı Paneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string Kullanıcı_Şifresi {
            get {
                return ResourceManager.GetString("Kullanıcı Şifresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Rights.
        /// </summary>
        internal static string Kullanım_Hakları {
            get {
                return ResourceManager.GetString("Kullanım Hakları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Maliyet {
            get {
                return ResourceManager.GetString("Maliyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Notification Text.
        /// </summary>
        internal static string Müşteri_Bilgilendirme_Metni {
            get {
                return ResourceManager.GetString("Müşteri Bilgilendirme Metni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Orijinal {
            get {
                return ResourceManager.GetString("Orijinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Para_Birimi {
            get {
                return ResourceManager.GetString("Para Birimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Currency.
        /// </summary>
        internal static string Para_Birimini_Kilitle {
            get {
                return ResourceManager.GetString("Para Birimini Kilitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Count.
        /// </summary>
        internal static string Satır_Sayısı {
            get {
                return ResourceManager.GetString("Satır Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Row Count.
        /// </summary>
        internal static string Satır_Sayısı_Belirle {
            get {
                return ResourceManager.GetString("Satır Sayısı Belirle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling.
        /// </summary>
        internal static string Satış {
            get {
                return ResourceManager.GetString("Satış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Remember.
        /// </summary>
        internal static string Şifre_Hatırla {
            get {
                return ResourceManager.GetString("Şifre Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string Şifremi_Hatırlat {
            get {
                return ResourceManager.GetString("Şifremi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string Sipariş_Detayları {
            get {
                return ResourceManager.GetString("Sipariş Detayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Order.
        /// </summary>
        internal static string Sipariş_Ekle {
            get {
                return ResourceManager.GetString("Sipariş Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp; Edit Orders.
        /// </summary>
        internal static string Siparişleri_Görüntüle___Düzenle {
            get {
                return ResourceManager.GetString("Siparişleri Görüntüle - Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Sıralama {
            get {
                return ResourceManager.GetString("Sıralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Şirketler {
            get {
                return ResourceManager.GetString("Şirketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stok {
            get {
                return ResourceManager.GetString("Stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Stock.
        /// </summary>
        internal static string Stok_Ekle {
            get {
                return ResourceManager.GetString("Stok Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Tablo {
            get {
                return ResourceManager.GetString("Tablo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Settings.
        /// </summary>
        internal static string Tablo_Kontrolleri {
            get {
                return ResourceManager.GetString("Tablo Kontrolleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string Toplam_İndirim {
            get {
                return ResourceManager.GetString("Toplam İndirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Tax.
        /// </summary>
        internal static string Toplam_İndirim_i_Genişlet {
            get {
                return ResourceManager.GetString("Toplam İndirim\'i Genişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amoun.
        /// </summary>
        internal static string Toplam_Tutar {
            get {
                return ResourceManager.GetString("Toplam Tutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Total.
        /// </summary>
        internal static string Toplam_Tutar_ı_Genişlet {
            get {
                return ResourceManager.GetString("Toplam Tutar\'ı Genişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string Türkçe {
            get {
                return ResourceManager.GetString("Türkçe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        internal static string Ürün_Bilgileri {
            get {
                return ResourceManager.GetString("Ürün Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit Product Details.
        /// </summary>
        internal static string Ürün_Bilgilerini_Düzenle {
            get {
                return ResourceManager.GetString("Ürün Bilgilerini Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product / Delete.
        /// </summary>
        internal static string Ürün_Düzenle___Sil {
            get {
                return ResourceManager.GetString("Ürün Düzenle / Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string Ürün_Ekle {
            get {
                return ResourceManager.GetString("Ürün Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Operations.
        /// </summary>
        internal static string Ürün_İşlemleri {
            get {
                return ResourceManager.GetString("Ürün İşlemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Ürünler {
            get {
                return ResourceManager.GetString("Ürünler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the Product.
        /// </summary>
        internal static string Ürünü_Sil {
            get {
                return ResourceManager.GetString("Ürünü Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Uygula {
            get {
                return ResourceManager.GetString("Uygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        internal static string Uygulamayı_Üstte_Tut {
            get {
                return ResourceManager.GetString("Uygulamayı Üstte Tut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Vergi {
            get {
                return ResourceManager.GetString("Vergi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Tax.
        /// </summary>
        internal static string VergiyiGenişlet {
            get {
                return ResourceManager.GetString("VergiyiGenişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch WhatsApp.
        /// </summary>
        internal static string WhatsApp_ı_Aç {
            get {
                return ResourceManager.GetString("WhatsApp\'ı Aç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Yenile {
            get {
                return ResourceManager.GetString("Yenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Yöntem {
            get {
                return ResourceManager.GetString("Yöntem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Day Report.
        /// </summary>
        internal static string Z_Raporu {
            get {
                return ResourceManager.GetString("Z Raporu", resourceCulture);
            }
        }
    }
}
