//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neoStockMasterv2.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Turkish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Turkish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neoStockMasterv2.Languages.Turkish", typeof(Turkish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış.
        /// </summary>
        internal static string Alış {
            get {
                return ResourceManager.GetString("Alış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Menü.
        /// </summary>
        internal static string Ana_Menü {
            get {
                return ResourceManager.GetString("Ana Menü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlaşmalı Kargo Şirketi.
        /// </summary>
        internal static string Anlaşmalı_Kargo_Şirketi {
            get {
                return ResourceManager.GetString("Anlaşmalı Kargo Şirketi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerimi Hatırlat.
        /// </summary>
        internal static string Bilgilerimi_Hatırlat {
            get {
                return ResourceManager.GetString("Bilgilerimi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Miktarı.
        /// </summary>
        internal static string Birim_Miktarı {
            get {
                return ResourceManager.GetString("Birim Miktarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çarpraz Kurlar.
        /// </summary>
        internal static string Çarpraz_Kurlar {
            get {
                return ResourceManager.GetString("Çarpraz Kurlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çevrilen.
        /// </summary>
        internal static string Çevrilen {
            get {
                return ResourceManager.GetString("Çevrilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çevrilmek İstenen.
        /// </summary>
        internal static string Çevrilmek_İstenen {
            get {
                return ResourceManager.GetString("Çevrilmek İstenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string Çıkış {
            get {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string Diğer {
            get {
                return ResourceManager.GetString("Diğer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolar.
        /// </summary>
        internal static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Bilgisi.
        /// </summary>
        internal static string Döviz_Bilgisi {
            get {
                return ResourceManager.GetString("Döviz Bilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        internal static string Düzenle {
            get {
                return ResourceManager.GetString("Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresinizi Yazınız.
        /// </summary>
        internal static string E_Mail_Adresinizi_Yazınız {
            get {
                return ResourceManager.GetString("E-Mail Adresinizi Yazınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenecek.
        /// </summary>
        internal static string Eklenecek {
            get {
                return ResourceManager.GetString("Eklenecek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English2 {
            get {
                return ResourceManager.GetString("English2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Geçmişi.
        /// </summary>
        internal static string Etkinlik_Geçmişi {
            get {
                return ResourceManager.GetString("Etkinlik Geçmişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel&apos;e Aktar.
        /// </summary>
        internal static string Excel_e_Aktar {
            get {
                return ResourceManager.GetString("Excel\'e Aktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        internal static string Fiyat {
            get {
                return ResourceManager.GetString("Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Hesapla - Sipariş Ekle.
        /// </summary>
        internal static string Fiyat_Hesapla___Sipariş_Ekle {
            get {
                return ResourceManager.GetString("Fiyat Hesapla - Sipariş Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genişlet.
        /// </summary>
        internal static string Genişlet {
            get {
                return ResourceManager.GetString("Genişlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Ekranı.
        /// </summary>
        internal static string Giriş_Ekranı {
            get {
                return ResourceManager.GetString("Giriş Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string Güncelle {
            get {
                return ResourceManager.GetString("Güncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Hatırla.
        /// </summary>
        internal static string ID_Hatırla {
            get {
                return ResourceManager.GetString("ID Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Geçmişi.
        /// </summary>
        internal static string IP_Geçmişi {
            get {
                return ResourceManager.GetString("IP Geçmişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Menüsü.
        /// </summary>
        internal static string İşlem_Menüsü {
            get {
                return ResourceManager.GetString("İşlem Menüsü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemi Seç.
        /// </summary>
        internal static string İşlemi_Seç {
            get {
                return ResourceManager.GetString("İşlemi Seç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Gün Sayısı.
        /// </summary>
        internal static string Kalan_Gün_Sayısı {
            get {
                return ResourceManager.GetString("Kalan Gün Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kâr Yüzdesi.
        /// </summary>
        internal static string Kâr_Yüzdesi {
            get {
                return ResourceManager.GetString("Kâr Yüzdesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo.
        /// </summary>
        internal static string Kargo {
            get {
                return ResourceManager.GetString("Kargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşılaştır.
        /// </summary>
        internal static string Karşılaştır {
            get {
                return ResourceManager.GetString("Karşılaştır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ekranı.
        /// </summary>
        internal static string Kayıt_Ekranı {
            get {
                return ResourceManager.GetString("Kayıt Ekranı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string Kayıt_Ol {
            get {
                return ResourceManager.GetString("Kayıt Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        internal static string Kayıt_Tarihi {
            get {
                return ResourceManager.GetString("Kayıt Tarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Gün Sayısı.
        /// </summary>
        internal static string Kayıtlı_Gün_Sayısı {
            get {
                return ResourceManager.GetString("Kayıtlı Gün Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        internal static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bilgileri.
        /// </summary>
        internal static string Kullanıcı_Bilgileri {
            get {
                return ResourceManager.GetString("Kullanıcı Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Detayları.
        /// </summary>
        internal static string Kullanıcı_Detayları {
            get {
                return ResourceManager.GetString("Kullanıcı Detayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı İsmi.
        /// </summary>
        internal static string Kullanıcı_İsmi {
            get {
                return ResourceManager.GetString("Kullanıcı İsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı İsmini Hatırlat.
        /// </summary>
        internal static string Kullanıcı_İsmini_Hatırlat {
            get {
                return ResourceManager.GetString("Kullanıcı İsmini Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Onaylama.
        /// </summary>
        internal static string Kullanıcı_Onaylama {
            get {
                return ResourceManager.GetString("Kullanıcı Onaylama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Paneli.
        /// </summary>
        internal static string Kullanıcı_Paneli {
            get {
                return ResourceManager.GetString("Kullanıcı Paneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Şifresi.
        /// </summary>
        internal static string Kullanıcı_Şifresi {
            get {
                return ResourceManager.GetString("Kullanıcı Şifresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Hakları.
        /// </summary>
        internal static string Kullanım_Hakları {
            get {
                return ResourceManager.GetString("Kullanım Hakları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maliyet.
        /// </summary>
        internal static string Maliyet {
            get {
                return ResourceManager.GetString("Maliyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string Onayla {
            get {
                return ResourceManager.GetString("Onayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orijinal.
        /// </summary>
        internal static string Orijinal {
            get {
                return ResourceManager.GetString("Orijinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        internal static string Para_Birimi {
            get {
                return ResourceManager.GetString("Para Birimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        internal static string Satış {
            get {
                return ResourceManager.GetString("Satış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Hatırla.
        /// </summary>
        internal static string Şifre_Hatırla {
            get {
                return ResourceManager.GetString("Şifre Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Hatırlat.
        /// </summary>
        internal static string Şifremi_Hatırlat {
            get {
                return ResourceManager.GetString("Şifremi Hatırlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişleri Görüntüle - Düzenle.
        /// </summary>
        internal static string Siparişleri_Görüntüle___Düzenle {
            get {
                return ResourceManager.GetString("Siparişleri Görüntüle - Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        internal static string Sıralama {
            get {
                return ResourceManager.GetString("Sıralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirketler.
        /// </summary>
        internal static string Şirketler {
            get {
                return ResourceManager.GetString("Şirketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        internal static string Stok {
            get {
                return ResourceManager.GetString("Stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Ekle.
        /// </summary>
        internal static string Stok_Ekle {
            get {
                return ResourceManager.GetString("Stok Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string Temizle {
            get {
                return ResourceManager.GetString("Temizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string Türkçe {
            get {
                return ResourceManager.GetString("Türkçe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurkFlag {
            get {
                object obj = ResourceManager.GetObject("TurkFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgileri.
        /// </summary>
        internal static string Ürün_Bilgileri {
            get {
                return ResourceManager.GetString("Ürün Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgilerini Düzenle.
        /// </summary>
        internal static string Ürün_Bilgilerini_Düzenle {
            get {
                return ResourceManager.GetString("Ürün Bilgilerini Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Düzenle / Sil.
        /// </summary>
        internal static string Ürün_Düzenle___Sil {
            get {
                return ResourceManager.GetString("Ürün Düzenle / Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ekle.
        /// </summary>
        internal static string Ürün_Ekle {
            get {
                return ResourceManager.GetString("Ürün Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün İşlemleri.
        /// </summary>
        internal static string Ürün_İşlemleri {
            get {
                return ResourceManager.GetString("Ürün İşlemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        internal static string Ürünler {
            get {
                return ResourceManager.GetString("Ürünler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü Sil.
        /// </summary>
        internal static string Ürünü_Sil {
            get {
                return ResourceManager.GetString("Ürünü Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamayı Üstte Tut.
        /// </summary>
        internal static string Uygulamayı_Üstte_Tut {
            get {
                return ResourceManager.GetString("Uygulamayı Üstte Tut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string Yenile {
            get {
                return ResourceManager.GetString("Yenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yöntem.
        /// </summary>
        internal static string Yöntem {
            get {
                return ResourceManager.GetString("Yöntem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Raporu.
        /// </summary>
        internal static string Z_Raporu {
            get {
                return ResourceManager.GetString("Z Raporu", resourceCulture);
            }
        }
    }
}
